### PR TITLE
Update index.tsx

### PR DESCRIPTION
**Pull request by tobyab**

### CODE REVIEW

**Comment by lachlanjc** [comment]
#### 📝 Changed routes:


| [**/**](https://hcb-wrapped-2023-nr9oivtpm.hackclub.dev/) |
|:-:|
|<a href="https://hcb-wrapped-2023-nr9oivtpm.hackclub.dev/">Screenshot of /</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/fONcxPDdSJDIP-oXwSOdNtzYk4cMsc_9UqmBw-M_KF5RSsko1mj1qAWMm2M1u-42gOwDyZUemmYe6M8ADxP0rA.png">(view full size)</a> |







Commit 8b3fadba0cb21dfed4b68e86c12559fd6d29bf6c (https://hcb-wrapped-2023-nr9oivtpm.hackclub.dev).

**Review by sampoder — APPROVED** [review]

**Comment by developedbytoby** [comment]
Just testing things!!

**Comment by tobyab** [comment]
Sorry @sampoder! Was just testing branch permissions. Wasn't a real PR. Forgot to close!

**Comment by sampoder** [comment]
oh dw you're all good

**Comment by sampoder** [comment]
i too was testing

**Pull request merged**
