### PR TITLE
implement most money spent by location and merchant 

### LINKED ISSUE #5: Where you & the org spent the most money (location & merchant)

### PR DESCRIPTION
**Pull request by ivoinestrachan**
implement most money spent by location and merchant 
rendering one org

fixing failed check

This closes #5 
#3

### CODE REVIEW

**Review by sampoder — CHANGES_REQUESTED** [review]
Let's have these stats be on two separate pages. I'm not sure what the best visual way of doing merchants is but I think for location stats they should be map-based. It'd also be interesting to borrow from Spotify some design (#9).

**Comment by ivoinestrachan** [comment]
alright let me take a look and see what I can do

**Comment by ivoinestrachan** [comment]
so something like this?
image

**Comment by sampoder** [comment]
Yeah - exactly!

**Comment by ivoinestrachan** [comment]
why is the pr failing?

**Review by sampoder — COMMENTED** [review]
We're getting some funky Typescript which seems to be causing deploys to fail:

```
Type error: No overload matches this call.
--
15:24:40.948 | Overload 1 of 2, '(predicate: (value: typeof TemplateSlide \| typeof HelloWorld, index: number, array: (typeof TemplateSlide \| typeof HelloWorld)[]) => value is typeof TemplateSlide \| typeof HelloWorld, thisArg?: any): (typeof TemplateSlide \| typeof HelloWorld)[]', gave the following error.
15:24:40.949 | Argument of type '({ config }: WrappedSlide) => boolean' is not assignable to parameter of type '(value: typeof TemplateSlide \| typeof HelloWorld, index: number, array: (typeof TemplateSlide \| typeof HelloWorld)[]) => value is typeof TemplateSlide \| typeof HelloWorld'.
15:24:40.949 | Types of parameters '__0' and 'value' are incompatible.
15:24:40.949 | Type 'typeof TemplateSlide \| typeof HelloWorld' is not assignable to type 'WrappedSlide'.
15:24:40.949 | Type 'typeof TemplateSlide' is not assignable to type 'WrappedSlide'.
15:24:40.951 | Type 'typeof TemplateSlide' is not assignable to type 'WrappedSlideComponent'.
15:24:40.951 | Types of parameters '__0' and 'props' are incompatible.
15:24:40.951 | Type 'SlideProps' is not assignable to type '{ data: Data; }'.
15:24:40.951 | The types of 'data.organizations' are incompatible between these types.
15:24:40.951 | Type '{ [key: string]: OrgData; }' is not assignable to type 'Record<string, OrganizationData>'.
15:24:40.951 | 'string' index signatures are incompatible.
15:24:40.951 | Type 'OrgData' is not assignable to type 'OrganizationData'.
15:24:40.952 | Types of property 'category' are incompatible.
15:24:40.952 | Type 'string \| null' is not assignable to type 'string'.
15:24:40.952 | Type 'null' is not assignable to type 'string'.
15:24:40.953 | Overload 2 of 2, '(predicate: (value: typeof TemplateSlide \| typeof HelloWorld, index: number, array: (typeof TemplateSlide \| typeof HelloWorld)[]) => unknown, thisArg?: any): (typeof TemplateSlide \| typeof HelloWorld)[]', gave the following error.
15:24:40.953 | Argument of type '({ config }: WrappedSlide) => boolean' is not assignable to parameter of type '(value: typeof TemplateSlide \| typeof HelloWorld, index: number, array: (typeof TemplateSlide \| typeof HelloWorld)[]) => unknown'.
15:24:40.953 | Types of parameters '__0' and 'value' are incompatible.
15:24:40.953 | Type 'typeof TemplateSlide \| typeof HelloWorld' is not assignable to type 'WrappedSlide'.
15:24:40.954 | Type 'typeof TemplateSlide' is not assignable to type 'WrappedSlide'.
```

**Comment by sampoder** [comment]
You can check builds locally by running the build script on your computer (`yarn build` or `npm run build`)

**Comment by ivoinestrachan** [comment]
thanks let me check this out

**Comment by sampoder** [comment]
Thoughts on using Mapbox for mapping?

**Comment by ivoinestrachan** [comment]
mapbox looks pretty good ill implement

**Comment by sampoder** [comment]
Update from me: https://hackclub.slack.com/archives/C054QL5JHU0/p1702101674904389

**Pull request closed without merging**
